dist: bionic
language: minimal

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="coq-elpi"
  matrix:
  - COQ="coqorg/coq:8.11" ELPI="elpi.1.11.2" CMD="make && make install"
  - COQ="coqorg/coq:8.11" ELPI="elpi.1.11.2" CMD="opam pin add coq-elpi . -y -v"

banches:
  only:
  - master
  - coq-master

install: |
  # Prepare the COQ container
  docker pull ${COQ}
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} ${COQ}
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    opam update -y
    opam install -y -v -j ${NJOBS} ${ELPI}
    opam config list; opam repo list; opam list
    " install
script:
- echo -e "${ANSI_YELLOW}Building ${CONTRIB_NAME}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
    ( ${CMD} )
    " script
- echo -en 'travis_fold:end:script\\r'

after_script:
- docker stop COQ  # optional but recommended