dist: trusty
sudo: required
language: c

git:
  submodules: false

install:
 - opam init -j 2 --compiler=4.02.3 -n -y
 - eval $(opam config env)
 - opam config var root
 - opam install -j 2 -y elpi
 - opam repo add coq-core-dev http://coq.inria.fr/opam/core-dev || true
 - opam repo add coq-extra-dev http://coq.inria.fr/opam/extra-dev || true

matrix:
  include:

  - env: TEST="opam package installation"
    os: linux
    addons:
      apt:
        sources:
        - avsm
        packages:
        - opam
    script:
    - opam pin remove coq-elpi -y || true
    - opam pin -y add coq-elpi "https://github.com/${TRAVIS_REPO_SLUG}.git#${TRAVIS_COMMIT}" -v
    - ls `opam config var lib`/coq/user-contrib/elpi/
    - opam remove coq-elpi
    - if [ -d `opam config var lib`/coq/user-contrib/elpi/ ]; then false; else true; fi
